Hawkeye-2204/FEC-Atelier

client/src/index.jsx
=> finished index file

template.html, webpack.config.js
inaccurate stars branch name oops! 
only change is adding template.html and making the change in weback config
=> added template.html

client/src/components/QA/Question.jsx, client/src/components/QA/QuestionsList.jsx
Thanks in advance for your review.
=> Submit a get request to retrieve all the answers to a specific question_id

client/src/assets/styles.css, client/src/components/App.jsx, client/src/components/RelatedItems/Main.jsx, client/src/components/RelatedItems/ProductsList.jsx
ProductList.jsx carousel is now functional with horizontal scroll; 
Added StyleApp on App.jsx to test out a standardized page with styled component on line 9 and line 19, the background is red for easy testing visibility, please feel free to alter it.
=> Functional carousel

client/src/components/QA/AnswersList.jsx, client/src/components/QA/Modals/ImageModal.css, client/src/components/QA/Modals/ImageModal.jsx, client/src/components/QA/Question.jsx, client/src/components/QA/QuestionsList.jsx, client/src/components/overview/Description.jsx, client/src/components/overview/Gallery.jsx
Thanks for your review in advance!
=> Pull images from answers and create modal for images.

client/src/assets/styles.css, client/src/components/RelatedItems/Main.jsx, client/src/components/RelatedItems/ProductCard.jsx
Added sample preview images; Added price; Added star ratings display; formatted each div display in card
=> Product Card:

client/src/components/QA/AnswersList.jsx, client/src/components/QA/Modals/ImageModal.css, client/src/components/QA/Modals/ImageModal.jsx
Thanks for the merge in advance.
=> Adjust ImageModal.jsx && .css to see current background content.

client/src/assets/styles.css, client/src/components/App.jsx, client/src/components/QA/AnswersList.jsx, client/src/components/QA/Modals/AddAnswerModal.jsx, client/src/components/QA/Question.jsx, client/src/components/QA/QuestionsList.jsx
Added seeMoreAnswers button
Added collapseAnswers button
Added Q&A widget styling
=> Added additional features for Q&A

client/src/assets/styles.css, client/src/components/App.jsx, client/src/components/RelatedItems/Main.jsx, client/src/components/RelatedItems/ProductCard.jsx, client/src/components/RelatedItems/ProductsList.jsx, client/src/tests/Related.test.js, package.json
CSS:
refactor style sheet into styled components on ProductsList.jsx and ProductCard.jsx
ProductCard:
created fontawesome icon star button, aboslute position on card; created container div for image and star b
utton; fixed image max heigth issue
ProductList:
Fixed carousel scroll issue to stop scroll when product list reaches end.
=> Product list detail

client/src/components/App.jsx, client/src/components/overview/Description.jsx, client/src/components/overview/Gallery.jsx, client/src/components/overview/ThumbGall.jsx
Implemented thumbnail carusoul for the image gallery
=> Gallerythmb

client/src/components/QA/AnswersList.jsx, client/src/components/QA/Question.jsx, client/src/components/QA/QuestionsList.jsx
Draw more answers from the API by setting count to 1000. Have useEffect rerender when modal submissions occur.
=> Rerender useEffect when add Q or A modals are submitted to API.

client/src/assets/styles.css, client/src/components/App.jsx, client/src/components/R&R/Legends/Characteristics.jsx, client/src/components/R&R/NewReview.jsx, client/src/components/R&R/Overview.jsx, client/src/components/R&R/ProductBreakdown.jsx, client/src/components/R&R/Rate.jsx, client/src/components/R&R/Ratings.jsx, client/src/components/R&R/ReviewTile.jsx, client/src/components/R&R/Reviews.jsx, client/src/components/R&R/Stars.jsx, server.js
everything should be working EXCEPT images -- need to figure out how to turn relative path into URL 
-- also, CSS for new review modal characteristics is ugly
=> almos good to go

client/src/components/QA/AnswersList.jsx, client/src/components/QA/Question.jsx, client/src/components/QA/QuestionsList.jsx
Helpful button for both Questions and Answers functions properly.
=> Completed Helpful Yes buttons for Questions and Answers

client/src/components/App.jsx, client/src/components/R&R/Overview.jsx, client/src/components/overview/Overview.jsx, client/src/components/overview/ProductInfo.jsx
=> fin scroll

client/src/components/RelatedItems/Comparison.jsx, client/src/components/RelatedItems/Main.jsx, client/src/components/RelatedItems/ProductCard.jsx, client/src/components/RelatedItems/ProductsList.jsx
comparison modal pull data based on current card id and current product
fix modal to pop over whole screen instead of under carousel
carousel scroll button only show if more products
product card resize text base on div
=> modal data pull & fix display on top ; carousel scroll button condition show; product card css

client/src/components/R&R/Bars.jsx, client/src/components/R&R/Overview.jsx, client/src/components/R&R/ProductBreakdown.jsx, client/src/components/R&R/Ratings.jsx, client/src/components/R&R/ReviewTile.jsx, client/src/components/R&R/Reviews.jsx
infinite scroll working with filters + sort too woohoooooo
=> infinite scroll

client/src/components/App.jsx, client/src/components/CartModal.jsx, client/src/components/HomePage.jsx, client/src/components/overview/AddCart.jsx, client/src/components/overview/Cart.jsx, client/src/components/overview/Description.jsx, client/src/components/overview/Dropdown.jsx, client/src/components/overview/Features.jsx, client/src/components/overview/Gallery.jsx, client/src/components/overview/IconGall.jsx, client/src/components/overview/Overview.jsx, client/src/components/overview/ProductInfo.jsx, client/src/components/overview/Style.jsx, client/src/components/overview/ThumbGall.jsx
Fixed CSS around my widget and also implemented darkmodes on cart and homepage
=> Fixing css

client/src/components/App.jsx, client/src/components/HomePage.jsx, client/src/components/Product.jsx, client/src/components/R&R/Bars.jsx, client/src/components/R&R/NewReview.jsx, client/src/components/R&R/ProductBreakdown.jsx, client/src/components/R&R/Reviews.jsx, client/src/components/RelatedItems/OutfitCard.jsx, client/src/components/RelatedItems/ProductCard.jsx, client/src/components/overview/ProductInfo.jsx
- changes w/ theme
- added cursor pointer onto related items
=> sticky nav bar

client/src/components/QA/AnswersList.jsx, client/src/components/QA/Question.jsx, client/src/components/QA/QuestionsList.jsx
removed transform from individual questions. caused side-effects for modals.
=> Punch list

client/src/components/QA/AnswersList.jsx, client/src/components/QA/Modals/AnswerModal.jsx, client/src/components/QA/Modals/QAModal.css, client/src/components/QA/Modals/QuestionModal.jsx, client/src/components/QA/Question.jsx, client/src/components/QA/QuestionsList.jsx
Thanks for the helper functions JZ!!!
=> Punch list - add image upload functionality

client/src/components/App.jsx, client/src/components/CartModal.jsx, client/src/components/Checkout.jsx, client/src/components/Form.jsx, client/src/components/overview/AddCart.jsx, client/src/components/overview/Dropdown.jsx
Added local storage to track cart -- this caused me to refactor other cart files
cartmodal now goes to new checkout page
new forms for user to input
checkout adds totals and completes purchase and resets cart and goes back to homepage
=> Checkout page

client/src/components/App.jsx, client/src/components/DarkMode/Toggler.jsx, client/src/components/overview/Overview.jsx, client/src/components/overview/ProductInfo.jsx
worked on responsiveness for overview and themetoggler to make it look nice on all devices
=> Overview responsive
